# Generated by Django 4.2.4 on 2025-06-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveau', '0001_initial'),
        ('annee_scolaire', '0001_initial'),
        ('groupe_classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.TextField()),
                ('genre', models.CharField(max_length=15)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleve/')),
                ('pere', models.CharField(max_length=191)),
                ('profession_pere', models.CharField(max_length=191)),
                ('contact_parent', models.CharField(blank=True, max_length=15, null=True)),
                ('mere', models.CharField(max_length=191)),
                ('profession_mere', models.CharField(max_length=191)),
                ('contact_mere', models.CharField(blank=True, max_length=15, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annee_scolaire.anneescolaire')),
                ('groupe_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupe_classe.groupeclasse')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niveau.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tranche1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tranche2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tranche3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_paye', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annee_scolaire.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_scolarites', to='eleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recu', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('frais_scolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.fraisscolarite')),
            ],
        ),
    ]
