# Generated by Django 4.2.4 on 2026-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0002_alter_eleve_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
