# Generated by Django 4.2.4 on 2026-01-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niveau', '0001_initial'),
        ('annee_scolaire', '0001_initial'),
        ('groupe_classe', '0001_initial'),
        ('eleve', '0003_eleve_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleveInscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annee_scolaire.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='eleve.eleve')),
                ('groupe_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupe_classe.groupeclasse')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niveau.niveau')),
            ],
            options={
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
