# Generated by Django 4.2.4 on 2025-09-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0001_initial'),
        ('groupe_classe', '0001_initial'),
        ('niveau', '0001_initial'),
        ('enseignant', '0002_alter_enseignant_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='Sexe',
            new_name='sexe',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='enseignant',
            unique_together={('nom', 'prenom')},
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupe_classe.groupeclasse')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveau.niveau')),
            ],
            options={
                'unique_together': {('enseignant', 'matiere', 'niveau', 'classe')},
            },
        ),
    ]
