# Generated by Django 4.2.4 on 2025-09-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0004_enseignant_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affectation',
        ),
    ]
