# Generated by Django 4.2.4 on 2026-09-06 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messagerie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Groupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupe",
                "verbose_name_plural": "Groupes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="MessageGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_groupes_envoyes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messagerie.groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de groupe",
                "verbose_name_plural": "Messages de groupe",
                "ordering": ["date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="MembreGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_adhesion", models.DateTimeField(auto_now_add=True)),
                ("administrateur", models.BooleanField(default=False)),
                ("actif", models.BooleanField(default=True)),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="messagerie.groupe",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations_groupes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre du groupe",
                "verbose_name_plural": "Membres des groupes",
                "ordering": ["date_adhesion"],
            },
        ),
        migrations.AddConstraint(
            model_name="membregroupe",
            constraint=models.UniqueConstraint(
                fields=("groupe", "utilisateur"), name="unique_membre_groupe"
            ),
        ),
    ]
