# Generated by Django 4.2.4 on 2026-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagerie", "0002_groupe_messagegroupe_membregroupe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="messages/audio/"),
        ),
        migrations.AddField(
            model_name="messagegroupe",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="messages/audio/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="contenu",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="messagegroupe",
            name="contenu",
            field=models.TextField(blank=True),
        ),
    ]
