# Generated by Django 4.2.4 on 2025-06-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveau.niveau')),
            ],
        ),
    ]
