# Generated by Django 4.2.4 on 2025-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=30, unique=True)),
                ('devise_ecole', models.CharField(max_length=30)),
                ('pays', models.CharField(max_length=30)),
                ('devise_pays', models.CharField(max_length=30)),
                ('ire', models.CharField(max_length=30)),
                ('dpe', models.CharField(max_length=30)),
                ('dsee', models.CharField(max_length=30)),
                ('date_creation', models.DateField()),
                ('logo', models.ImageField(upload_to='ecole')),
            ],
        ),
    ]
