# Generated by Django 4.2.4 on 2025-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='meapu',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
