# Generated by Django 4.2.4 on 2025-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0003_etablissement_meapu'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='responsable',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
