# Generated by Django 4.2.4 on 2025-09-22 14:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0004_etablissement_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
