# Generated by Django 4.2.4 on 2025-09-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupe_classe', '0001_initial'),
        ('niveau', '0001_initial'),
        ('enseignant', '0004_enseignant_user'),
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.enseignant')),
                ('groupe_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupe_classe.groupeclasse')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveau.niveau')),
            ],
            options={
                'unique_together': {('enseignant', 'matiere', 'niveau', 'groupe_classe')},
            },
        ),
    ]
