# Generated by Django 4.2.4 on 2025-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveau', '0001_initial'),
        ('matiere', '0002_enseignantmatiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'niveau')},
        ),
    ]
