# Generated by Django 4.2.4 on 2025-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0001_initial'),
        ('eleve', '0002_alter_eleve_photo'),
        ('annee_scolaire', '0001_initial'),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_finale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_comp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_cours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('eleve', 'matiere', 'trimestre', 'annee_scolaire')},
        ),
    ]
