# Generated by Django 4.2.4 on 2026-02-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0004_eleveinscrit'),
        ('note', '0002_note_note_finale_alter_note_note_comp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleve.eleveinscrit'),
        ),
        migrations.AlterField(
            model_name='note',
            name='trimestre',
            field=models.PositiveIntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3')]),
        ),
    ]
