# Generated by Django 4.2.4 on 2026-02-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annee_scolaire', '0001_initial'),
        ('eleve', '0004_eleveinscrit'),
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinannuel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='bulletintrimestriel',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleve.eleveinscrit'),
        ),
        migrations.AddField(
            model_name='bulletintrimestriel',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleve.eleveinscrit'),
        ),
        migrations.AlterField(
            model_name='bulletintrimestriel',
            name='trimestre',
            field=models.PositiveIntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3')]),
        ),
        migrations.AlterUniqueTogether(
            name='bulletinannuel',
            unique_together={('eleve', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='bulletintrimestriel',
            unique_together={('eleve', 'trimestre', 'annee_scolaire')},
        ),
    ]
