# Generated by Django 4.2.4 on 2026-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_alter_bulletinannuel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinannuel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bulletintrimestriel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bulletinannuel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bulletintrimestriel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bulletintrimestriel',
            name='trimestre',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='bulletinannuel',
            name='inscription',
        ),
        migrations.RemoveField(
            model_name='bulletintrimestriel',
            name='inscription',
        ),
    ]
